### ISSUE TITLE
DefaultFileMiddlware doesn't work with EmbeddedFileProvider and subfolders.

### ISSUE THREAD

**Issue by pakrym** [aspnet/StaticFiles#141]
Repro:
**Embed the following directory structure:** 
```
└───wwwroot
    │
    └───Files
            TextFile.txt
```

**Use the folowing code:**
```
  var fs = new EmbeddedFileProvider(this.GetType().GetTypeInfo().Assembly, "StaticFilesSignoff.wwwroot");;
            app.UseDefaultFiles(new DefaultFilesOptions()
            {
                DefaultFileNames = new[] { "TextFile.txt" },
                FileProvider = fs
            });
            app.UseFileServer(new FileServerOptions()
            {
                FileProvider = fs,
            });
```

**Go to `http://localhost:5000/Files/`**

Expected `TextFile.txt` content gets displayed
Actual: 404

**Comment by Tratcher** [comment]
This happens because DefaultFiles first checks if the directory exists, and EmbeddedFileProvider doesn't support directories. We should try making EmbeddedFileProvider smarter around directories.
https://github.com/aspnet/StaticFiles/blob/dev/src/Microsoft.AspNetCore.StaticFiles/DefaultFilesMiddleware.cs#L69-L70

**Comment by muratg** [comment]
Dup of https://github.com/aspnet/FileSystem/issues/206
