### ISSUE TITLE
Remove etags from StaticFiles

### ISSUE THREAD

**Issue by muratg** [aspnet/StaticFiles#159]

**Comment by henryhe9999** [comment]
Why?

**Comment by Tratcher** [comment]
There is concern that the e-tag generation algorithm is not sufficient. Right now it only considers the length of the file and the last modified date. Hashing the actual contents of the file would be too resource intensive.

Note these concerns are theoretical, no customer issues have been reported and this algorithm has been in use for 3+ years (Katana and ASP.NET Core).

**Comment by davidfowl** [comment]
> Note these concerns are theoretical, no customer issues have been reported and this algorithm has been in use for 3+ years (Katana and ASP.NET Core).

Nobody complained about the performance of the static file middleware in katana because it was likely very rarely used over IIS. The performance is pretty abysmal in comparison.

It might be worth looking at what other file server implementations do to generate etags.

**Comment by muratg** [comment]
Since this is a breaking change, triaging in 2.0.0 for now.

**Comment by RehanSaeed** [comment]
Any updates on what the story here is going to be for 2.0?

**Comment by ChadNedzlek** [comment]
This needs to at least be an option. The overly simplistic algorithm is causing collisions (since changing the file slight slight recently after it was previously modified is totally normal). Which causes our site to just fall apart as we get mismatched JS files. It just broke one of our production deployments, and we have very few options to fix the issue other than to random touch files until the site works again.

**Comment by Tratcher** [comment]
@ChadNedzlek Yours is the first report of this being a problem in the wild. Can you give some more details on how it broke? E.g. before and after examples of the size, date, and etag?

**Comment by ChadNedzlek** [comment]
Unfortunately, I can't manage to get it to reproduce anymore... I rebuilt all the files and redeployed to our production server to unblock our customers and everything seems to have changed.

I'm not sure what the exact state was, unfortunately, but we'd only changed the file a small bit (and it was only 5800 bytes, which should have fit in the noise of the FileTime), but the browsers were (incorrectly) caching some of the files returned from app.UseStaticFiles() and not others.

**Comment by bgever** [comment]
We've hit exactly the same issue in a production environment, and appears to be caused by a browser *feature*, and not the ETag algorithm.

Hitting refresh (with caching enabled) repeatedly should show that sometimes the browser will not reload all static resources from the server, and instead load from cache. In chrome denoted with `(from file cache)` or `(from memory cache)` after the HTTP status code.

The same problem is described in https://github.com/bhauman/lein-figwheel/pull/464 where you can also find a link to the [Chromium blog confirming this behavior](https://blog.chromium.org/2017/01/reload-reloaded-faster-and-leaner-page_26.html).

>  To improve the stale content use case, Chrome now has a simplified reload behavior to only validate the main resource and continue with a regular page load.

As discussed in the linked PR, the use of the `Cache-Control: no-cache` header should force the browser to always contact the server, and since it still sends the `If-None-Match` header due to the `ETag` of the previous response, the new request will be responded with a `HTTP 304 Not Modified`.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2453
