### ISSUE TITLE
Feature Request: Files without extension or .json extension are not served

### ISSUE THREAD

**Issue by borgdylan** [aspnet/StaticFiles#25]
I tries to server a a json file named 1.json by means of the static files middleware and i got a 404. However when i changed the extension to .txt, the file was served.

**Comment by Tratcher** [comment]
By design. See https://github.com/aspnet/StaticFiles/blob/dev/src/Microsoft.AspNet.StaticFiles/FileExtensionContentTypeProvider.cs

The static file middleware uses the file extension to look up the content-type, and will only serve files with known & allowed content-types by default. ".json" is not listed and therefor will not be served by default. You can add it to the list if you want to serve them.

Files without extensions cannot match the table and will not be served by default. You can set StaticFileOptions.ServeUnknownFileTypes=true to override this. In that scenario you should also set some content-type via DefaultContentType or OnPrepareResponse.
