### ISSUE TITLE
Additional MIME types

### ISSUE THREAD

**Issue by vbnewb** [aspnet/StaticFiles#28]
I know that I can add additional ones myself but I was wondering if there was a specific reason why woff2 hadn't made it in yet. Thanks in advance!

**Comment by Eilon** [comment]
I believe the current list is based on what IIS / ASP.NET historically used by default. A tricky aspect of changing the default list here is that if the web server (e.g. IIS) does its own static file handling, changing the MIME mappings here won't do anything because the Static File middleware won't be used. However, it's perhaps fair to consider that user error; that is, the user has to configure their web server appropriately no matter what, and each web server has its own configuration requirements.

So, if you have MIME mappings that you think are reasonably common, please log a bug on the specific MIME mapping you think should be added (because we use bugs to generate READMEs), and if you're interested, send a PR as well.

**Comment by Praburaj** [comment]
I think we should add this MIME type. In katana we added this already. Probably this was missed from porting. 
http://katanaproject.codeplex.com/SourceControl/diff/file/view/24aa43641adac57cb5bd523b77bdc0ced9f0455d?fileId=src%2FMicrosoft.Owin.StaticFiles%2FContentTypes%2FFileExtensionContentTypeProvider.cs

**Comment by RehanSaeed** [comment]
Please also add the following MIME types which I have found to be missing:

- .json - application/json (This one is pretty unbelievable)
- .ttc - application/x-font-ttf
- .webp - image/webp
- .appcache - text/cache-manifest
- .manifest - text/cache-manifest

Also the following MIME types need updating:

- .ttf should be application/x-font-ttf and not application/octet-stream

**Comment by Eilon** [comment]
@RehanSaeed can you log a new issue for these?

**Comment by RehanSaeed** [comment]
@Eilon I've created a new Pull Request https://github.com/aspnet/StaticFiles/compare/dev...RehanSaeed:patch-1

**Comment by Eilon** [comment]
Can you log a bug too? We need bugs in the system so that we can track which issues were fixed when we generate release notes.

**Comment by RehanSaeed** [comment]
Done https://github.com/aspnet/StaticFiles/issues/63
